# Generated by Django 6.0.2 on 2026-03-12 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_codeverify_is_active_alter_codeverify_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeverify',
            name='is_active',
        ),
    ]
