# Generated by Django 6.0.2 on 2026-03-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_codeverify_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeverify',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
